---
#apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-aws-secrets
spec:
  provider: aws
  # definition for your K8s secret
  secretObjects:
  - secretName: secrets-manager-json  # k8s secret name
    type: Opaque # type of k8s secret
    # content of your k8s secret
    data:
    - objectName: dbuseralias
      key: k8s-env-key-for-dbuser
    - objectName: dbpasswordalias
      key: k8s-env-key-for-dbpassword
  parameters:
    # filters to retrieve AWS Secret and it's keys
    objects: | 
        - objectName: "exchange-app-db-secrets"
          objectType: "secretsmanager"
          jmesPath:
              - Path: "dbuser"
                ObjectAlias: "dbuseralias"
              - Path: "dbpassword"
                ObjectAlias: "dbpasswordalias"

# object alias in parameters should be same as objectName in secretObjects